### ISSUE TITLE
Sonos fails to initialize

### ISSUE THREAD

**Issue by billburgess** [nfarina/homebridge-legacy-plugins#3]
Using same config as before, but under new home bridge plugin, Sonos fails to initialize.

Loading 1 platforms...
[Speaker] Initializing Sonos platform...
Loading legacy platform Sonos
/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Sonos.js:66
    this.name = this.description["roomName"] + " " + this.config["name"];
                                ^

TypeError: Cannot read property 'roomName' of undefined
    at Object.SonosAccessory (/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Sonos.js:66:33)
    at new <anonymous> (/usr/local/lib/node_modules/homebridge-legacy-plugins/index.js:36:16)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:194:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:34:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:22:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

**Comment by nfarina** [comment]
I suspect this was caused by #1 - could you update and try again?

**Comment by billburgess** [comment]
---

## Loaded config.json with 3 accessories and 1 platforms.

Loading 1 platforms...
[Speaker] Initializing Sonos platform...
Loading legacy platform Sonos
/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Sonos.js:66
    this.name = this.description["roomName"] + " " + this.config["name"];
                                ^

TypeError: Cannot read property 'roomName' of undefined
    at Object.SonosAccessory (/usr/local/lib/node_modules/homebridge-legacy-plugins/platforms/Sonos.js:66:33)
    at new <anonymous> (/usr/local/lib/node_modules/homebridge-legacy-plugins/index.js:36:16)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:195:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:35:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)

**Comment by billburgess** [comment]
I updated and it still has the same error.

**Comment by nfarina** [comment]
Sorry, I meant update homebridge main, not this repo :)
